version: '3'
services:
  mongodb:
    image:  mongo
    networks:
      - production-network
  
  node1:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: emersonc/persons
    container_name: persons
    ports:
      - "3000"
    networks:
      - production-network
    depends_on:
      - "mongodb"

networks:
  production-network:
    driver: bridge